version: '3.1'
services:
  web:
    container_name: odoo_web
    image: odoo_web
    build: ./
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/enterprise-addons
      - ./addons:/mnt/extra-addons
      - ./addons/paulundernst:/mnt/extra-addons/paulundernst
      - ./addons/scrimo_addons:/mnt/extra-addons/scrimo_addons
      - ./addons/scrimo_documents:/mnt/extra-addons/scrimo_documents
      - ./addons/scrimo_layout:/mnt/extra-addons/scrimo_layout
      - ./addons/scrimo_purchase:/mnt/extra-addons/scrimo_purchase
      - ./addons/scrimo_timesheet:/mnt/extra-addons/scrimo_timesheet
      - ./addons/scrimo_unfollow:/mnt/extra-addons/scrimo_unfollow
      - ./addons/ninja:/mnt/extra-addons/ninja
      - ./addons/prt_mail_messages:/mnt/extra-addons/prt_mail_messages
      - ./addons/export:/mnt/extra-addons/export
      - ./addons/scrimo_time_odoo:/mnt/extra-addons/scrimo_time_odoo
    command: -u all
    environment:
      SMTP_SERVER: mail
      SMTP_PORT: 1025
  db:
    container_name: odoo_db
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: odoo_db_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  mail:
    container_name: odoo_mail
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  odoo-web-data:
  odoo-db-data: